module.exports.errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  PASSWORD_DO_NOT_MATCH: 'PASSWORD_DO_NOT_MATCH',
  PASSWORD_RULES_DO_NOT_MATCH: 'PASSWORD_RULES_DO_NOT_MATCH',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  BLOCKED_USER: 'BLOCKED_USER',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN'
};
